<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int $user_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $type  default: (NULL), max length: 20, raw type: varchar
 * @property string|null $subject_type  default: (NULL), max length: 50, raw type: varchar
 * @property int|null $subject_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $name  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $info  default: (NULL), raw type: text
 * @property string|null $sn  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $ip  default: (NULL), max length: 255, raw type: varchar
 * @property \SimpleRecord\DateTime|null $add_time  default: (NULL), max length: 19, raw type: datetime
 * @property string|null $context  default: (NULL), max length: 1000, raw type: varchar
 */
class admin_operation_log extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_admin_operation_log';
    static $primary_key = 'id';
}
