<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 10, raw type: int
 * @property string|null $contact_name  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $qq  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $qq_group  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $mobile  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $telephone  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $wechat  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $foxdou_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $info  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property string|null $template_id  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 */
class admin_template_contact extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_admin_template_contact';
    static $primary_key = 'id';
}
