<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string $user_name  default: (NULL), max length: 20, raw type: varchar
 * @property string $password  default: (NULL), max length: 100, raw type: varchar
 * @property string|null $name  default: (NULL), max length: 20, raw type: varchar
 * @property string|null $mobile  default: (NULL), max length: 20, raw type: varchar
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property string $roles  default: (10), max length: 255, raw type: varchar
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 * @property string|null $avatar_url  default: (NULL), max length: 255, raw type: varchar
 * @property string $status  default: (1), max length: 20, raw type: varchar
 * @property string|null $gender  default: (NULL), max length: 6, raw type: varchar
 * @property string|null $title  default: (NULL), max length: 20, raw type: varchar
 * @property int|null $last_login_time  default: (NULL), max length: 11, raw type: int
 * @property string|null $last_login_ip  default: (NULL), max length: 20, raw type: varchar
 * @property int|null $is_deleted  default: (0), max length: 11, raw type: int
 * @property int|null $deleted_at  default: (NULL), max length: 11, raw type: int
 * @property int|null $lock_expires_at  default: (NULL), max length: 11, raw type: int
 * @property int|null $password_error_num  default: (0), max length: 11, raw type: int
 */
class admins extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_admins';
    static $primary_key = 'id';
}
