<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $user_id  default: (NULL), max length: 11, raw type: int
 * @property float $profit  default: (NULL), max length: 17, raw type: decimal
 * @property int $date  default: (NULL), max length: 11, raw type: int
 * @property int $add_time  default: (NULL), max length: 11, raw type: int
 */
class agent_users_profit_count_by_day extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_agent_users_profit_count_by_day';
    
}
