<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int $user_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $view  default: (NULL), max length: 255, raw type: varchar
 * @property string $print_type  default: (0), max length: 20, raw type: varchar
 * @property string $content  default: (NULL), max length: 1000, raw type: varchar
 */
class agent_users_print_settings extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_agent_users_print_settings';
    static $primary_key = 'id';
}
