<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $product_id  default: (NULL), max length: 11, raw type: int
 * @property int $product_type  default: (NULL), max length: 11, raw type: int
 * @property float $life_real_sell_price  default: (NULL), max length: 17, raw type: decimal
 * @property int $user_id  default: (NULL), max length: 11, raw type: int
 * @property int $add_time  default: (NULL), max length: 11, raw type: int
 * @property int $edit_time  default: (0), max length: 11, raw type: int
 */
class agent_users_product_life_real_sell_price extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_agent_users_product_life_real_sell_price';
    static $primary_key = 'user_id';
}
