<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string $trade_sn  default: (NULL), max length: 27, raw type: char
 * @property string $order_sn  default: (), max length: 27, raw type: varchar
 * @property string $name  default: (NULL), max length: 255, raw type: varchar
 * @property string $info  default: (), max length: 255, raw type: varchar
 * @property float $rebate  default: (NULL), max length: 17, raw type: decimal
 * @property float $after_rebate_balance  default: (NULL), max length: 17, raw type: decimal
 * @property float $after_pintai_rebate_balance  default: (NULL), max length: 17, raw type: decimal
 * @property int $dealer_user_id  default: (NULL), max length: 11, raw type: int
 * @property int $user_id  default: (0), max length: 11, raw type: int
 * @property int $rebate_type  default: (0), max length: 1, raw type: tinyint
 * @property int $add_time  default: (0), max length: 11, raw type: int
 */
class agent_users_rebate_log extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_agent_users_rebate_log';
    static $primary_key = 'id';
}
