<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string $cookie  default: (NULL), raw type: text
 * @property string $bill_user_id  default: (NULL), max length: 255, raw type: varchar
 * @property string $collection_account  default: (NULL), max length: 255, raw type: varchar
 */
class alipay_cookies extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_alipay_cookies';
    static $primary_key = 'id';
}
