<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 10, raw type: int
 * @property string $areaname  default: (NULL), max length: 50, raw type: varchar
 * @property int $parentid  default: (NULL), max length: 10, raw type: int
 * @property string|null $shortname  default: (NULL), max length: 50, raw type: varchar
 * @property int|null $areacode  default: (NULL), max length: 6, raw type: int
 * @property int|null $zipcode  default: (NULL), max length: 10, raw type: int
 * @property string|null $pinyin  default: (NULL), max length: 100, raw type: varchar
 * @property string|null $lng  default: (NULL), max length: 20, raw type: varchar
 * @property string|null $lat  default: (NULL), max length: 20, raw type: varchar
 * @property int $level  default: (NULL), max length: 1, raw type: tinyint
 * @property string $position  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $sort  default: (50), max length: 3, raw type: tinyint
 */
class area extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_area';
    static $primary_key = 'id';
}
