<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int|null $portal_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $name  default: (NULL), max length: 50, raw type: varchar
 * @property int|null $level  default: (1), max length: 11, raw type: int
 * @property int|null $parent_id  default: (0), max length: 11, raw type: int
 * @property int|null $user_type  default: (0), max length: 255, raw type: tinyint
 * @property \SimpleRecord\DateTime|null $created_at  default: (NULL), max length: 19, raw type: datetime
 * @property \SimpleRecord\DateTime|null $updated_at  default: (NULL), max length: 19, raw type: datetime
 */
class articles_categories extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_articles_categories';
    static $primary_key = 'id';
}
