<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int|null $portal_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $cate_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $label_id  default: (NULL), max length: 50, raw type: varchar
 * @property string|null $title  default: (NULL), max length: 50, raw type: varchar
 * @property string|null $abstract  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $keywords  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $cover_image_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $cover_image_url  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $content  default: (NULL), raw type: text
 * @property string|null $source  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $editor_id  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $published  default: (NULL), max length: 5, raw type: tinyint
 * @property int|null $view_count  default: (0), max length: 255, raw type: int
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $publish_time  default: (NULL), max length: 11, raw type: int
 */
class articles extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_articles';
    static $primary_key = 'id';
}
