<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int $parent_id  default: (NULL), max length: 11, raw type: int
 * @property int $child_id  default: (NULL), max length: 11, raw type: int
 */
class auth_admin_item_relation extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_auth_admin_item_relation';
    static $primary_key = 'id';
}
