<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string $name  default: (NULL), max length: 80, raw type: varchar
 * @property int $item_type  default: (NULL), max length: 4, raw type: tinyint
 * @property string|null $route  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $rule_class  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $rule_data  default: (NULL), raw type: blob
 * @property string|null $description  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $allow_type  default: (1), max length: 4, raw type: tinyint
 * @property int $request_type  default: (0), max length: 4, raw type: tinyint
 * @property string|null $group  default: (0), max length: 50, raw type: varchar
 * @property string|null $category  default: (0), max length: 50, raw type: varchar
 */
class auth_admin_item extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_auth_admin_item';
    static $primary_key = 'id';
}
