<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int|null $file_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $object_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $object_type  default: (NULL), max length: 20, raw type: varchar
 */
class file_refs extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_file_refs';
    
}
