<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int|null $operator_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $operator_prefix  default: (NULL), max length: 3, raw type: int
 * @property int $number_prefix  default: (NULL), max length: 7, raw type: int
 * @property string $province_name  default: (NULL), max length: 20, raw type: varchar
 * @property string $city_name  default: (NULL), max length: 20, raw type: varchar
 * @property string $name  default: (NULL), max length: 20, raw type: varchar
 * @property string $post_code  default: (NULL), max length: 20, raw type: varchar
 * @property string $area_code  default: (NULL), max length: 20, raw type: varchar
 * @property string $city_code  default: (NULL), max length: 20, raw type: varchar
 * @property string|null $types  default: (NULL), max length: 50, raw type: varchar
 * @property int $is_mvno  default: (0), max length: 1, raw type: tinyint
 * @property string|null $mvno_isp  default: (NULL), max length: 20, raw type: varchar
 * @property int $mvno  default: (0), max length: 11, raw type: int
 * @property string $province_code  default: (NULL), max length: 20, raw type: varchar
 * @property int $status  default: (1), max length: 4, raw type: tinyint
 * @property string|null $note  default: (NULL), max length: 100, raw type: varchar
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (1), max length: 11, raw type: int
 * @property \SimpleRecord\DateTime|null $created_at  default: (NULL), max length: 19, raw type: datetime
 * @property \SimpleRecord\DateTime|null $updated_at  default: (NULL), max length: 19, raw type: datetime
 */
class icp extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_icp';
    static $primary_key = 'id';
}
