<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string|null $prefix  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $phone  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $province  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $city  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $isp  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $post_code  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $city_code  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $area_code  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $types  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $senfen_code  default: (NULL), max length: 255, raw type: varchar
 * @property int $status_icp  default: (1), max length: 1, raw type: tinyint
 * @property int $if_mvno  default: (NULL), max length: 1, raw type: tinyint
 * @property string|null $mvno_isp  default: (NULL), max length: 255, raw type: varchar
 * @property int $mvno  default: (NULL), max length: 11, raw type: int
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (1), max length: 11, raw type: int
 */
class icp_tel extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_icp_tel';
    static $primary_key = 'id';
}
