<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int|null $interface_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $code  default: (NULL), max length: 11, raw type: int
 * @property string|null $interface  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $msg  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 */
class interface_err_code extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_interface_err_code';
    static $primary_key = 'id';
}
