<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int $interface_id  default: (NULL), max length: 11, raw type: int
 * @property string $name  default: (), max length: 255, raw type: varchar
 * @property string $type  default: (), max length: 255, raw type: varchar
 * @property string $explain  default: (), max length: 255, raw type: varchar
 * @property int $add_time  default: (NULL), max length: 11, raw type: int
 * @property int $edit_time  default: (NULL), max length: 11, raw type: int
 * @property int $parent_id  default: (0), max length: 11, raw type: int
 * @property string $example  default: (), max length: 255, raw type: varchar
 */
class interface_return_params extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_interface_return_params';
    static $primary_key = 'id';
}
