<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property string $version  default: (NULL), max length: 180, raw type: varchar
 * @property int|null $apply_time  default: (NULL), max length: 11, raw type: int
 */
class migration extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_migration';
    static $primary_key = 'version';
}
