<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int $number  default: (NULL), max length: 20, raw type: bigint
 * @property float $price  default: (0), max length: 10, raw type: decimal
 * @property int $status  default: (0), max length: 1, raw type: tinyint
 * @property string|null $info  default: (NULL), max length: 255, raw type: varchar
 * @property int $type  default: (0), max length: 1, raw type: tinyint
 * @property int $user_type  default: (0), max length: 1, raw type: tinyint
 * @property int $add_time  default: (0), max length: 11, raw type: int
 * @property int $reg_time  default: (0), max length: 11, raw type: int
 * @property int|null $edit_time  default: (0), max length: 11, raw type: int
 */
class number extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_number';
    static $primary_key = 'id';
}
