<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property float $balance  default: (0), max length: 12, raw type: decimal
 * @property int|null $user_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $platform_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $sign_key  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $level  default: (NULL), max length: 11, raw type: int
 * @property int|null $add_time  default: (0), max length: 11, raw type: int
 * @property string $status  default: (INACTIVE), max length: 16, raw type: varchar
 * @property float $disable_money  default: (0), max length: 17, raw type: decimal
 * @property int $parent_dealer_user_id  default: (0), max length: 11, raw type: int
 * @property int $edit_time  default: (0), max length: 11, raw type: int
 * @property int|null $group_id  default: (NULL), max length: 11, raw type: int
 */
class open_users extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_open_users';
    static $primary_key = 'id';
}
