<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int|null $user_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $cause  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 */
class open_users_aduit_log extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_open_users_aduit_log';
    static $primary_key = 'id';
}
