<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int|null $order_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $provider_id  default: (NULL), max length: 16, raw type: varchar
 * @property string|null $recharge_status  default: (NULL), max length: 16, raw type: varchar
 * @property int|null $recharge_sequence  default: (NULL), max length: 11, raw type: int
 * @property string|null $official_sn  default: (NULL), max length: 64, raw type: varchar
 * @property string|null $settle_status  default: (NULL), max length: 16, raw type: varchar
 * @property int|null $can_recharge  default: (NULL), max length: 11, raw type: int
 * @property int|null $careful_status  default: (NULL), max length: 11, raw type: int
 * @property string|null $recharge_ip  default: (NULL), max length: 32, raw type: varchar
 * @property \SimpleRecord\DateTime|null $created_at  default: (NULL), max length: 19, raw type: datetime
 * @property \SimpleRecord\DateTime|null $updated_at  default: (NULL), max length: 19, raw type: datetime
 */
class order_recharge_supplier_orders extends \App\Common\Model\BaseModel {
    static $table_name  = 'order_recharge_supplier_orders';
    static $primary_key = 'id';
}
