<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property string $id  default: (NULL), max length: 36, raw type: varchar
 * @property string|null $trade_id  default: (NULL), max length: 36, raw type: varchar
 * @property string|null $outer_sn  default: (NULL), max length: 50, raw type: varchar
 * @property int $product_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $product_sub_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $product_sub_type  default: (NULL), max length: 5, raw type: varchar
 * @property int|null $source_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $request_id  default: (0), max length: 11, raw type: bigint
 * @property int $platform_id  default: (NULL), max length: 1, raw type: int
 * @property int|null $order_cate_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $product_master_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $product_cate_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $product_name  default: (NULL), max length: 255, raw type: varchar
 * @property float|null $product_face_value  default: (NULL), max length: 10, raw type: decimal
 * @property int $user_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $supplier_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $operator_id  default: (0), max length: 4, raw type: int
 * @property string|null $phone_number  default: (NULL), max length: 120, raw type: varchar
 * @property string|null $on_before_info  default: (), max length: 255, raw type: varchar
 * @property string|null $on_after_info  default: (), max length: 255, raw type: varchar
 * @property string|null $on_other  default: (), max length: 255, raw type: varchar
 * @property float|null $recharge_amount  default: (NULL), max length: 10, raw type: decimal
 * @property int|null $payment_class_id  default: (NULL), max length: 1, raw type: int
 * @property int|null $recharge_method  default: (NULL), max length: 1, raw type: int
 * @property int|null $recharge_sequence  default: (NULL), max length: 11, raw type: int
 * @property float|null $buy_num  default: (1), max length: 11, raw type: decimal
 * @property float|null $paid_amount  default: (0), max length: 12, raw type: decimal
 * @property float|null $sell_price  default: (NULL), max length: 12, raw type: decimal
 * @property int $settlement_status  default: (0), max length: 4, raw type: tinyint
 * @property string|null $status  default: (NULL), max length: 30, raw type: varchar
 * @property string|null $user_ip  default: (), max length: 130, raw type: varchar
 * @property string|null $recharge_ip  default: (), max length: 130, raw type: varchar
 * @property string|null $note  default: (), max length: 120, raw type: varchar
 * @property int|null $app_id  default: (0), max length: 11, raw type: int
 * @property float|null $real_sell_price  default: (0), max length: 17, raw type: decimal
 * @property \SimpleRecord\DateTime|null $add_time  default: (NULL), max length: 19, raw type: datetime
 * @property \SimpleRecord\DateTime|null $pay_time  default: (NULL), max length: 19, raw type: datetime
 * @property \SimpleRecord\DateTime|null $edit_time  default: (NULL), max length: 19, raw type: datetime
 * @property \SimpleRecord\DateTime|null $end_time  default: (NULL), max length: 19, raw type: datetime
 * @property string|null $speed  default: (1), max length: 8, raw type: varchar
 * @property string|null $province_name  default: (), max length: 10, raw type: varchar
 * @property string|null $city_name  default: (), max length: 20, raw type: varchar
 * @property int|null $mvno  default: (0), max length: 4, raw type: tinyint
 * @property string|null $admin_info  default: (), max length: 255, raw type: varchar
 * @property string|null $order_mark  default: (NULL), max length: 20, raw type: varchar
 * @property string|null $provider_id  default: (NULL), max length: 16, raw type: varchar
 * @property string|null $current_sup_order_id  default: (NULL), max length: 36, raw type: varchar
 */
class order_recharge extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_order_recharge';
    static $primary_key = 'id';
}
