<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string $sup_order_id  default: (), max length: 36, raw type: varchar
 * @property string $order_id  default: (NULL), max length: 36, raw type: varchar
 * @property string $order_status  default: (NULL), max length: 255, raw type: varchar
 * @property string $recharge_status  default: (NULL), max length: 255, raw type: varchar
 * @property string $settle_status  default: (NULL), max length: 255, raw type: varchar
 * @property int $operation_user_id  default: (NULL), max length: 11, raw type: int
 * @property int $if_admin  default: (0), max length: 1, raw type: tinyint
 * @property string $operator_ip  default: (NULL), max length: 255, raw type: varchar
 * @property int $operation_type  default: (0), max length: 1, raw type: tinyint
 * @property \SimpleRecord\DateTime $add_time  default: (NULL), max length: 19, raw type: datetime
 * @property \SimpleRecord\DateTime $edit_time  default: (NULL), max length: 19, raw type: datetime
 */
class order_recharge_sup_status_operation_log extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_order_recharge_sup_status_operation_log';
    static $primary_key = 'id';
}
