<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property string $sup_sn  default: (NULL), max length: 30, raw type: varchar
 * @property string $order_sn  default: (NULL), max length: 30, raw type: varchar
 * @property string $official_sn  default: (), max length: 255, raw type: varchar
 * @property int $sup_order_cate  default: (NULL), max length: 11, raw type: int
 * @property string $t_sn  default: (NULL), max length: 20, raw type: varchar
 * @property int $sup_user_id  default: (0), max length: 11, raw type: int
 * @property int $source_id  default: (NULL), max length: 11, raw type: int
 * @property float $source_mianzi  default: (NULL), max length: 10, raw type: decimal
 * @property float $source_buy_num  default: (NULL), max length: 11, raw type: decimal
 * @property float $sup_cost  default: (0), max length: 12, raw type: decimal
 * @property float $sup_price  default: (0), max length: 12, raw type: decimal
 * @property string $on_before_info  default: (), max length: 255, raw type: varchar
 * @property string $on_after_info  default: (), max length: 255, raw type: varchar
 * @property string $on  default: (NULL), max length: 120, raw type: varchar
 * @property string $on_other  default: (), max length: 255, raw type: varchar
 * @property int $recharge_status  default: (NULL), max length: 2, raw type: tinyint
 * @property int $recharge_sequence  default: (0), max length: 11, raw type: int
 * @property int $closing_status  default: (1), max length: 1, raw type: tinyint
 * @property int $can_recharge  default: (0), max length: 1, raw type: tinyint
 * @property string $sup_admin_info  default: (), max length: 255, raw type: varchar
 * @property \SimpleRecord\DateTime $add_time  default: (NULL), max length: 19, raw type: datetime
 * @property \SimpleRecord\DateTime $end_time  default: (NULL), max length: 19, raw type: datetime
 * @property string $sup_info  default: (), max length: 255, raw type: varchar
 * @property int $careful_status  default: (0), max length: 1, raw type: tinyint
 * @property int $sup_speed  default: (1), max length: 4, raw type: tinyint
 * @property string $source_product_name  default: (NULL), max length: 255, raw type: varchar
 * @property int $source_product_cate_id  default: (NULL), max length: 11, raw type: int
 * @property int $source_product_master_id  default: (0), max length: 11, raw type: int
 * @property int $source_product_unit  default: (3), max length: 1, raw type: tinyint
 * @property string $province  default: (), max length: 10, raw type: varchar
 * @property string $city  default: (), max length: 20, raw type: varchar
 * @property int $mvno  default: (0), max length: 4, raw type: tinyint
 * @property int $icp  default: (0), max length: 4, raw type: tinyint
 * @property string $recharge_ip  default: (), max length: 130, raw type: varchar
 */
class order_recharge_sup_beifen extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_order_recharge_sup_beifen';
    static $primary_key = 'sup_sn';
}
