<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int|null $p_t_id  default: (0), max length: 11, raw type: int
 * @property int|null $pinlv_id  default: (0), max length: 11, raw type: int
 * @property int|null $ci  default: (0), max length: 11, raw type: int
 * @property int|null $tian  default: (0), max length: 11, raw type: int
 * @property int|null $user_level  default: (NULL), max length: 11, raw type: int
 * @property int|null $package  default: (0), max length: 11, raw type: int
 */
class payment_template_pinlv_ci extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_payment_template_pinlv_ci';
    static $primary_key = 'id';
}
