<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string|null $name  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $explain  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $remark  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $type_name  default: (NULL), max length: 100, raw type: varchar
 * @property int|null $type_value  default: (NULL), max length: 11, raw type: int
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 */
class payment_template extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_payment_template';
    static $primary_key = 'id';
}
