<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int|null $p_t_id  default: (0), max length: 11, raw type: int
 * @property int|null $pinlv_id  default: (0), max length: 11, raw type: int
 * @property float $price  default: (NULL), max length: 10, raw type: decimal
 * @property float $chaoprice  default: (NULL), max length: 10, raw type: decimal
 * @property float|null $manyuan  default: (0), max length: 10, raw type: decimal
 * @property float|null $songci  default: (0), max length: 10, raw type: decimal
 * @property int|null $shifouzhuanshu  default: (NULL), max length: 1, raw type: tinyint
 * @property int $user_level  default: (NULL), max length: 11, raw type: int
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 */
class payment_template_pinlv_price extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_payment_template_pinlv_price';
    static $primary_key = 'id';
}
