<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int $way_id  default: (1), max length: 11, raw type: int
 * @property string $img  default: (NULL), max length: 255, raw type: varchar
 * @property int $type  default: (1), max length: 1, raw type: tinyint
 * @property string|null $info  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 */
class payment_institution extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_payment_institution';
    static $primary_key = 'id';
}
