<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int $pintai  default: (0), max length: 1, raw type: tinyint
 * @property string $name  default: (NULL), max length: 255, raw type: varchar
 * @property string $english_name  default: (NULL), max length: 255, raw type: varchar
 * @property int $is_user_reg_aduit_geren  default: (1), max length: 1, raw type: tinyint
 * @property int $is_user_reg_aduit_geti  default: (1), max length: 1, raw type: tinyint
 * @property int $is_user_reg_aduit_qiye  default: (1), max length: 1, raw type: tinyint
 */
class pintai_config extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_pintai_config';
    static $primary_key = 'id';
}
