<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string|null $name  default: (NULL), max length: 50, raw type: varchar
 * @property string|null $info  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $default  default: (0), max length: 1, raw type: tinyint
 * @property int $is_deleted  default: (0), max length: 4, raw type: tinyint
 * @property int $platform_id  default: (NULL), max length: 1, raw type: tinyint
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 */
class platform_user_level extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_platform_user_level';
    static $primary_key = 'id';
}
