<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 20, raw type: bigint
 * @property int $product_id  default: (NULL), max length: 20, raw type: bigint
 * @property string $name  default: (NULL), max length: 32, raw type: varchar
 * @property string|null $value  default: (NULL), max length: 1024, raw type: varchar
 */
class product_attributes extends \App\Common\Model\BaseModel {
    static $table_name  = 'product_attributes';
    static $primary_key = 'id';
}
