<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int $master_id  default: (NULL), max length: 11, raw type: int
 * @property int $face_value_type  default: (1), max length: 1, raw type: tinyint
 * @property string $num  default: (1), max length: 100, raw type: varchar
 * @property float $face_value  default: (NULL), max length: 10, raw type: decimal
 * @property int $status  default: (1), max length: 1, raw type: tinyint
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 */
class product_common extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_product_common';
    static $primary_key = 'id';
}
