<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string|null $card_number  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $card_password  default: (NULL), max length: 255, raw type: varchar
 * @property float|null $card_face_value  default: (NULL), max length: 11, raw type: decimal
 * @property string|null $card_type  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $end_use_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $status  default: (NULL), max length: 1, raw type: tinyint
 */
class product_suorce_mobile_rechargeable_card extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_product_suorce_mobile_rechargeable_card';
    static $primary_key = 'id';
}
