<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string $url  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $params  default: (NULL), raw type: text
 * @property string|null $response  default: (NULL), raw type: text
 * @property \SimpleRecord\DateTime $add_time  default: (NULL), max length: 19, raw type: datetime
 */
class request_log_sup_api extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_request_log_sup_api';
    static $primary_key = 'id';
}
