<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string $username  default: (NULL), max length: 25, raw type: varchar
 * @property string|null $password  default: (NULL), max length: 100, raw type: varchar
 */
class s extends \App\Common\Model\BaseModel {
    static $table_name  = 'users';
    static $primary_key = 'id';
}
