<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string|null $ip  default: (NULL), max length: 500, raw type: varchar
 * @property int|null $app_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $user_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 */
class safe_ip_open extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_safe_ip_open';
    static $primary_key = 'id';
}
