<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string|null $name  default: (NULL), max length: 32, raw type: varchar
 * @property string|null $subject_type  default: (NULL), max length: 20, raw type: varchar
 * @property string|null $title  default: (NULL), max length: 100, raw type: varchar
 * @property int|null $platform_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $payload  default: (NULL), raw type: text
 * @property int|null $enabled  default: (NULL), max length: 11, raw type: int
 * @property string|null $status  default: (NULL), max length: 16, raw type: varchar
 * @property \SimpleRecord\DateTime|null $scheduled_at  default: (NULL), max length: 19, raw type: datetime
 * @property int|null $run_once  default: (NULL), max length: 11, raw type: int
 * @property int|null $creator_user_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $canceller_user_id  default: (NULL), max length: 11, raw type: int
 * @property \SimpleRecord\DateTime|null $created_at  default: (NULL), max length: 19, raw type: datetime
 * @property \SimpleRecord\DateTime|null $updated_at  default: (NULL), max length: 19, raw type: datetime
 */
class scheduled_jobs extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_scheduled_jobs';
    static $primary_key = 'id';
}
