<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property string $id  default: (NULL), max length: 32, raw type: varchar
 * @property string|null $name  default: (NULL), max length: 255, raw type: varchar
 * @property int $sell_time  default: (0), max length: 11, raw type: int
 * @property int $product_cate_id  default: (NULL), max length: 1, raw type: tinyint
 * @property int|null $loser_limit  default: (0), max length: 11, raw type: int
 * @property int $auto_refund  default: (0), max length: 1, raw type: tinyint
 * @property string|null $info  default: (NULL), max length: 255, raw type: varchar
 * @property int $sell_user_id  default: (0), max length: 11, raw type: int
 * @property int $status  default: (0), max length: 1, raw type: tinyint
 * @property string|null $review_status  default: (NULL), max length: 12, raw type: varchar
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 * @property int $supply_type  default: (1), max length: 1, raw type: tinyint
 * @property string|null $contact_id  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $sn  default: (NULL), max length: 32, raw type: varchar
 */
class sell_template extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_sell_template';
    static $primary_key = 'id';
}
