<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property string $val  default: (NULL), max length: 32, raw type: varchar
 * @property int $app_id  default: (NULL), max length: 11, raw type: int
 * @property int $add_time  default: (NULL), max length: 11, raw type: int
 */
class servicemall_api_request_sn_log extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_servicemall_api_request_sn_log';
    static $primary_key = 'val';
}
