<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string|null $name  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $pid  default: (0), max length: 11, raw type: int
 */
class service_cate extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_service_cate';
    static $primary_key = 'id';
}
