<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int $service_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $name  default: (NULL), max length: 50, raw type: varchar
 * @property string|null $content  default: (NULL), raw type: text
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 */
class service_explain extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_service_explain';
    static $primary_key = 'id';
}
