<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int $user_id  default: (NULL), max length: 11, raw type: int
 * @property string $name  default: (NULL), max length: 50, raw type: varchar
 * @property int $sex  default: (NULL), max length: 1, raw type: tinyint
 * @property string $cred_number  default: (NULL), max length: 50, raw type: varchar
 * @property string|null $img_cred  default: (NULL), max length: 255, raw type: varchar
 * @property string $img_zen  default: (NULL), max length: 255, raw type: varchar
 * @property string $img_fan  default: (NULL), max length: 255, raw type: varchar
 * @property string $img_souci  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $expiry_time_start  default: (NULL), max length: 11, raw type: int
 * @property int|null $expiry_time_end  default: (NULL), max length: 11, raw type: int
 * @property int $long_time  default: (NULL), max length: 1, raw type: tinyint
 * @property int $verify  default: (0), max length: 1, raw type: tinyint
 * @property int|null $img_cred_verify  default: (NULL), max length: 1, raw type: tinyint
 * @property int|null $img_zen_verify  default: (0), max length: 1, raw type: tinyint
 * @property int|null $img_fan_verify  default: (0), max length: 1, raw type: tinyint
 * @property int|null $img_souci_verify  default: (0), max length: 1, raw type: tinyint
 * @property string $address  default: (NULL), max length: 255, raw type: varchar
 */
class simin_verify_log extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_simin_verify_log';
    static $primary_key = 'id';
}
