<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string|null $section  default: (NULL), max length: 50, raw type: varchar
 * @property string|null $name  default: (NULL), max length: 50, raw type: varchar
 * @property string|null $value  default: (NULL), max length: 1000, raw type: varchar
 * @property string|null $note  default: (NULL), max length: 100, raw type: varchar
 */
class system_settings extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_system_settings';
    static $primary_key = 'id';
}
