<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int|null $top_operator_id  default: (NULL), max length: 11, raw type: int
 * @property string $name  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $enabled  default: (NULL), max length: 11, raw type: int
 * @property \SimpleRecord\DateTime|null $created_at  default: (NULL), max length: 19, raw type: datetime
 * @property \SimpleRecord\DateTime|null $updated_at  default: (NULL), max length: 19, raw type: datetime
 */
class tencent_product_categories extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_tencent_product_categories';
    static $primary_key = 'id';
}
