<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property string $id  default: (NULL), max length: 36, raw type: varchar
 * @property int|null $user_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $platform_id  default: (NULL), max length: 11, raw type: int
 * @property int $order_cate  default: (NULL), max length: 11, raw type: int
 * @property string|null $order_id  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $trade_sn  default: (NULL), max length: 255, raw type: varchar
 * @property float|null $order_amount  default: (NULL), max length: 10, raw type: decimal
 * @property float|null $total_amount  default: (NULL), max length: 10, raw type: decimal
 * @property string|null $note  default: (NULL), max length: 50, raw type: varchar
 * @property string|null $sub_third_party_order_sn  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $third_party_trade_sn  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $pay_status  default: (NULL), max length: 1, raw type: tinyint
 * @property string|null $product_name  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $out_pay_user_accounts  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $payment_class_id  default: (NULL), max length: 11, raw type: int
 * @property float|null $poundage  default: (NULL), max length: 4, raw type: decimal
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 */
class third_party_pay_log extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_third_party_pay_log';
    static $primary_key = 'id';
}
