<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string|null $name  default: (NULL), max length: 255, raw type: varchar
 * @property int $way_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $picture  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $poundage_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $status  default: (NULL), max length: 1, raw type: tinyint
 * @property int|null $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 */
class user_pay_way_auxiliary extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_user_pay_way_auxiliary';
    static $primary_key = 'id';
}
