<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string $type  default: (NULL), max length: 1, raw type: char
 * @property string $status  default: (INACTIVE), max length: 10, raw type: varchar
 * @property string $real_name_status  default: (INCOMPLETE), max length: 20, raw type: char
 * @property int|null $business_type  default: (NULL), max length: 11, raw type: int
 * @property string|null $user_name  default: (), max length: 50, raw type: char
 * @property string|null $nick_name  default: (NULL), max length: 50, raw type: varchar
 * @property string|null $roles  default: (NULL), max length: 100, raw type: varchar
 * @property string|null $login_nick_name  default: (NULL), max length: 50, raw type: varchar
 * @property string|null $head_img  default: (/img/default-head-portrait.jpg), max length: 255, raw type: varchar
 * @property string|null $mobile  default: (NULL), max length: 15, raw type: varchar
 * @property string|null $bind_mobile  default: (NULL), max length: 50, raw type: varchar
 * @property string|null $email  default: (NULL), max length: 50, raw type: varchar
 * @property string|null $bind_email  default: (NULL), max length: 50, raw type: varchar
 * @property int|null $email_verified  default: (0), max length: 11, raw type: int
 * @property string $password  default: (NULL), max length: 100, raw type: varchar
 * @property string|null $pay_password  default: (NULL), max length: 100, raw type: varchar
 * @property int $is_deleted  default: (0), max length: 1, raw type: tinyint
 * @property string $pay_status  default: (N), max length: 1, raw type: char
 * @property int|null $password_error_num  default: (0), max length: 11, raw type: int
 * @property int|null $pay_password_error_num  default: (0), max length: 11, raw type: int
 * @property float|null $balance  default: (0), max length: 12, raw type: decimal
 * @property string|null $register_ip  default: (NULL), max length: 16, raw type: varchar
 * @property string|null $info  default: (NULL), max length: 100, raw type: varchar
 * @property int $add_time  default: (NULL), max length: 11, raw type: int
 * @property int|null $edit_time  default: (NULL), max length: 11, raw type: int
 * @property string|null $opened_platform  default: (NULL), max length: 50, raw type: varchar
 * @property string $is_open_platform  default: (N), max length: 10, raw type: varchar
 * @property string $is_agent_platform  default: (N), max length: 10, raw type: varchar
 * @property string $is_supplier_platform  default: (N), max length: 10, raw type: varchar
 * @property string $other_user_data  default: ({}), max length: 255, raw type: varchar
 * @property string|null $last_login_ip  default: (NULL), max length: 16, raw type: varchar
 * @property int|null $last_login_time  default: (NULL), max length: 11, raw type: int
 * @property string|null $avatar_url  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $referrer_id  default: (NULL), max length: 11, raw type: int
 * @property string $is_entry_identity_info  default: (N), max length: 10, raw type: varchar
 * @property string $open_methods  default: (), max length: 50, raw type: varchar
 * @property string $assign_account  default: (N), raw type: enum
 * @property string $is_safe_question  default: (N), raw type: enum
 */
class users extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_users';
    static $primary_key = 'id';
}
