<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $register_user_id  default: (NULL), max length: 11, raw type: int
 * @property int $inviter_user_id  default: (NULL), max length: 11, raw type: int
 * @property int $add_time  default: (NULL), max length: 11, raw type: int
 */
class users_invite_register_log extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_users_invite_register_log';
    static $primary_key = 'register_user_id';
}
