<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property string $id  default: (NULL), max length: 36, raw type: varchar
 * @property string|null $trade_sn  default: (NULL), max length: 36, raw type: varchar
 * @property string|null $outer_sn  default: (NULL), max length: 50, raw type: varchar
 * @property int|null $cate_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $outer_content  default: (NULL), max length: 255, raw type: varchar
 * @property int $platform_id  default: (NULL), max length: 1, raw type: int
 * @property int|null $scene_id  default: (NULL), max length: 11, raw type: int
 * @property int|null $user_id  default: (NULL), max length: 11, raw type: int
 * @property string $note  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $payment_class_id  default: (NULL), max length: 2, raw type: int
 * @property int|null $payment_auxiliary_id  default: (0), max length: 11, raw type: int
 * @property string|null $collection_account  default: (NULL), max length: 255, raw type: varchar
 * @property int $recharge_way  default: (0), max length: 2, raw type: tinyint
 * @property float $amount  default: (NULL), max length: 17, raw type: decimal
 * @property float|null $poundage  default: (NULL), max length: 7, raw type: decimal
 * @property float|null $current_balance  default: (NULL), max length: 17, raw type: decimal
 * @property string $status  default: (0), max length: 16, raw type: varchar
 * @property float|null $platform_total_balance  default: (NULL), max length: 18, raw type: decimal
 * @property int $add_time  default: (NULL), max length: 11, raw type: int
 * @property string|null $product_name  default: (NULL), max length: 100, raw type: varchar
 */
class user_balance_recharge_orders extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_user_balance_recharge_orders';
    static $primary_key = 'id';
}
