<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int $user_id  default: (NULL), max length: 11, raw type: int
 * @property int $platform_id  default: (0), max length: 1, raw type: tinyint
 * @property int $type  default: (1), max length: 1, raw type: tinyint
 * @property string $title  default: (), max length: 64, raw type: varchar
 * @property int $status  default: (1), max length: 1, raw type: tinyint
 * @property string $content  default: (), max length: 255, raw type: varchar
 * @property int|null $add_time  default: (0), max length: 11, raw type: int
 * @property int|null $edit_time  default: (0), max length: 11, raw type: int
 */
class users_message extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_users_message';
    static $primary_key = 'id';
}
