<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 255, raw type: int
 * @property int $user_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $contact_name  default: (NULL), max length: 50, raw type: varchar
 * @property string|null $contact_phone  default: (NULL), max length: 20, raw type: varchar
 * @property string|null $contact_mail  default: (NULL), max length: 20, raw type: varchar
 * @property string|null $contact_qq  default: (NULL), max length: 20, raw type: varchar
 * @property string|null $contact_address  default: (NULL), max length: 255, raw type: varchar
 * @property \SimpleRecord\DateTime|null $add_time  default: (NULL), max length: 19, raw type: datetime
 * @property \SimpleRecord\DateTime|null $edit_time  default: (NULL), max length: 19, raw type: datetime
 */
class users_contact extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_users_contact';
    static $primary_key = 'id';
}
