<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int $platform_id  default: (NULL), max length: 1, raw type: int
 * @property int $user_id  default: (0), max length: 11, raw type: int
 * @property string $foxdou_user_name  default: (), max length: 255, raw type: varchar
 * @property string $trade_id  default: (), max length: 36, raw type: varchar
 * @property string $alipay_sn  default: (NULL), max length: 255, raw type: varchar
 * @property string $collection_account  default: (NULL), max length: 30, raw type: varchar
 * @property string $alipay_user_name  default: (NULL), max length: 255, raw type: varchar
 * @property float $amount  default: (NULL), max length: 10, raw type: decimal
 * @property string $alipay_user_account  default: (NULL), max length: 255, raw type: varchar
 * @property string $alipay_user_id  default: (NULL), max length: 30, raw type: char
 * @property \SimpleRecord\DateTime $alipay_time  default: (NULL), max length: 19, raw type: datetime
 * @property int $add_time  default: (NULL), max length: 11, raw type: int
 * @property int $status  default: (NULL), max length: 1, raw type: tinyint
 * @property string $alipay_trans_memo  default: (), max length: 255, raw type: varchar
 */
class user_money_alipay_transfer_recharge_log extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_user_money_alipay_transfer_recharge_log';
    static $primary_key = 'alipay_sn';
}
