<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property string|null $status  default: (PENDING), max length: 20, raw type: varchar
 * @property int $user_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $entity_type  default: (), max length: 1, raw type: varchar
 * @property string|null $entity_name  default: (NULL), max length: 100, raw type: varchar
 * @property string|null $entity_license_no  default: (NULL), max length: 32, raw type: varchar
 * @property string|null $entity_license_address  default: (NULL), max length: 255, raw type: varchar
 * @property \SimpleRecord\DateTime|null $entity_license_valid_from  default: (NULL), max length: 10, raw type: date
 * @property \SimpleRecord\DateTime|null $entity_license_valid_to  default: (NULL), max length: 10, raw type: date
 * @property int|null $entity_license_valid_long_term  default: (NULL), max length: 11, raw type: int
 * @property int|null $entity_license_front_image_id  default: (NULL), max length: 11, raw type: bigint
 * @property string|null $entity_license_front_image_url  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $entity_license_front_image_review_result  default: (0), max length: 10, raw type: varchar
 * @property int|null $entity_license_back_image_id  default: (NULL), max length: 11, raw type: bigint
 * @property string|null $entity_license_back_image_review_result  default: (NULL), max length: 10, raw type: varchar
 * @property string|null $entity_license_back_image_url  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $entity_license_handheld_image_id  default: (NULL), max length: 11, raw type: bigint
 * @property string|null $entity_license_handheld_image_review_result  default: (NULL), max length: 10, raw type: varchar
 * @property string|null $entity_license_handheld_image_url  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $entity_license_business_scopes  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $biz_legal_representative_name  default: (NULL), max length: 20, raw type: varchar
 * @property string|null $biz_legal_representative_id_no  default: (NULL), max length: 32, raw type: varchar
 * @property \SimpleRecord\DateTime|null $biz_legal_representative_id_valid_from  default: (NULL), max length: 10, raw type: date
 * @property \SimpleRecord\DateTime|null $biz_legal_representative_id_valid_to  default: (NULL), max length: 10, raw type: date
 * @property int|null $biz_legal_representative_id_valid_long_term  default: (NULL), max length: 11, raw type: int
 * @property int|null $biz_legal_representative_id_front_image_id  default: (NULL), max length: 11, raw type: bigint
 * @property string|null $biz_legal_representative_id_front_image_url  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $biz_legal_representative_id_front_image_review_result  default: (NULL), max length: 10, raw type: varchar
 * @property int|null $biz_legal_representative_id_back_image_id  default: (NULL), max length: 11, raw type: bigint
 * @property string|null $biz_legal_representative_id_back_image_url  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $biz_legal_representative_id_back_image_review_result  default: (NULL), max length: 10, raw type: varchar
 * @property int|null $biz_legal_representative_id_handheld_image_id  default: (NULL), max length: 20, raw type: bigint
 * @property string|null $biz_legal_representative_id_handheld_image_url  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $biz_legal_representative_id_handheld_image_review_result  default: (NULL), max length: 10, raw type: varchar
 * @property int|null $status_info  default: (0), max length: 1, raw type: tinyint
 * @property string|null $submission_ip  default: (NULL), max length: 20, raw type: varchar
 * @property \SimpleRecord\DateTime|null $created_at  default: (NULL), max length: 6, raw type: datetime
 * @property \SimpleRecord\DateTime|null $updated_at  default: (NULL), max length: 6, raw type: datetime
 * @property \SimpleRecord\DateTime|null $submitted_at  default: (NULL), max length: 6, raw type: datetime
 * @property \SimpleRecord\DateTime|null $basic_reviewed_at  default: (NULL), max length: 6, raw type: datetime
 * @property \SimpleRecord\DateTime|null $full_reviewed_at  default: (NULL), max length: 6, raw type: datetime
 * @property \SimpleRecord\DateTime|null $verified_at  default: (NULL), max length: 19, raw type: datetime
 * @property \SimpleRecord\DateTime|null $rejected_at  default: (NULL), max length: 19, raw type: datetime
 * @property string|null $province_code  default: (NULL), max length: 10, raw type: varchar
 * @property string|null $city_code  default: (NULL), max length: 10, raw type: varchar
 * @property string|null $district_code  default: (NULL), max length: 10, raw type: varchar
 * @property int|null $certification_level  default: (0), max length: 1, raw type: tinyint
 * @property string|null $review_status  default: (PENDING), max length: 20, raw type: varchar
 * @property string|null $note  default: (), max length: 255, raw type: varchar
 */
class users_identities extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_users_identities';
    static $primary_key = 'id';
}
