<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int $user_id  default: (0), max length: 11, raw type: int
 * @property int $platform_id  default: (0), max length: 1, raw type: tinyint
 * @property string $referrer_account  default: (), max length: 50, raw type: varchar
 * @property string $status  default: (PENDING), raw type: enum
 * @property string $note  default: (), max length: 255, raw type: varchar
 * @property int $add_time  default: (0), max length: 11, raw type: int
 * @property int $edit_time  default: (0), max length: 11, raw type: int
 */
class users_account_application extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_users_account_application';
    static $primary_key = 'id';
}
