<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int|null $user_id  default: (NULL), max length: 11, raw type: int
 * @property string|null $mobile  default: (NULL), max length: 50, raw type: varchar
 * @property string|null $ip  default: (NULL), max length: 255, raw type: varchar
 * @property string|null $info  default: (NULL), max length: 255, raw type: varchar
 * @property int|null $time  default: (NULL), max length: 11, raw type: int
 * @property string|null $type  default: (NULL), max length: 50, raw type: varchar
 */
class user_log_agent extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_user_log_agent';
    static $primary_key = 'id';
}
