<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 11, raw type: int
 * @property int $user_id  default: (NULL), max length: 11, raw type: int
 * @property string $pass  default: (), max length: 50, raw type: varchar
 * @property string $account  default: (), max length: 20, raw type: varchar
 * @property int $method  default: (1), max length: 1, raw type: tinyint
 * @property int $platform_id  default: (0), max length: 1, raw type: tinyint
 * @property int $status  default: (0), max length: 1, raw type: tinyint
 * @property int $add_time  default: (0), max length: 11, raw type: int
 */
class users_open_account_log extends \App\Common\Model\BaseModel {
    static $table_name  = 'yzb_users_open_account_log';
    static $primary_key = 'id';
}
