<?php

// THIS FILE IS AUTO GENERATED FROM DATABASE TABLES
// DO NOT EDIT THIS FILE, OR YOUR MODIFICATIONS WILL BE LOST.
 
namespace App\Common\Model\AutoGenerated;

/**
 * @property int $id  default: (NULL), max length: 10, raw type: int
 * @property string|null $title  default: (NULL), max length: 254, raw type: char
 * @property string|null $content  default: (NULL), raw type: text
 * @property string|null $author  default: (NULL), max length: 60, raw type: char
 * @property string|null $title_fc  default: (NULL), max length: 254, raw type: char
 * @property string|null $content_fc  default: (NULL), raw type: text
 */
class zzx_articles extends \App\Common\Model\BaseModel {
    static $table_name  = 'zzx_articles';
    static $primary_key = 'id';
}
