<?php
namespace App\Common\Model\OpenPlatform;

use App\Common\Model\AutoGenerated\request_api_log_open;

class ApiRequestLog extends request_api_log_open {

    static $table_name = 'yzb_request_api_log_open';

    const STATUS_SUCCEED = 1;
    const STATUS_FAILED  = 0;

    const STATUSES = [
        self::STATUS_FAILED  => '失败',
        self::STATUS_SUCCEED => '成功'
    ];
}
