<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.NhBd0iO' shared service.

return $this->privates['.service_locator.NhBd0iO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'alipayService' => array('privates', 'App\\Common\\Bundle\\SimplePay\\Service\\AlipayService', 'getAlipayServiceService.php', true),
));
