<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DmTkD_n' shared service.

return $this->privates['.service_locator.DmTkD_n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'helper' => array('services', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService.php', true),
));
