<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.F.dW8Vu' shared service.

return $this->privates['.service_locator.F.dW8Vu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'ispManager' => array('privates', 'App\\Common\\Service\\IspManager', 'getIspManagerService.php', true),
    'orderService' => array('privates', 'App\\Common\\Service\\Order\\OrderService', 'getOrderServiceService.php', true),
    'productService' => array('privates', 'App\\Reseller\\Service\\ProductService', 'getProductServiceService.php', true),
    'settingManager' => array('privates', 'App\\Common\\Service\\SystemSettingManager', 'getSystemSettingManagerService.php', true),
    'urlGenerator' => array('services', 'router', 'getRouterService', false),
));
