<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dlf6qch' shared service.

return $this->privates['.service_locator.dlf6qch'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'recaptchaService' => array('privates', 'App\\Common\\Service\\RecaptchaService', 'getRecaptchaServiceService.php', true),
    'smsService' => array('privates', 'App\\Common\\Service\\SmsService', 'getSmsServiceService.php', true),
));
