<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SvuyVJk' shared service.

return $this->privates['.service_locator.SvuyVJk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'mailer' => array('services', 'swiftmailer.mailer.mxhichina', 'getSwiftmailer_Mailer_MxhichinaService.php', true),
    'recaptchaService' => array('privates', 'App\\Common\\Service\\RecaptchaService', 'getRecaptchaServiceService.php', true),
));
