<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7fGS9UX' shared service.

return $this->privates['.service_locator.7fGS9UX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'form' => array('privates', 'Symfu\\SimpleFormBundle\\Form', 'getFormService.php', true),
    'identityVerifyService' => array('privates', 'App\\Common\\Service\\ExternalService\\IdentityVerifyService', 'getIdentityVerifyServiceService.php', true),
    'mailer' => array('services', 'swiftmailer.mailer.mxhichina', 'getSwiftmailer_Mailer_MxhichinaService.php', true),
    'settings' => array('privates', 'App\\Common\\Service\\SystemSetting', 'getSystemSettingService', false),
));
