<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.jcyut7p' shared service.

return $this->privates['.service_locator.jcyut7p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'ispManager' => array('privates', 'App\\Common\\Service\\IspManager', 'getIspManagerService.php', true),
    'orderService' => array('privates', 'App\\Common\\Service\\Order\\OrderService', 'getOrderServiceService.php', true),
    'userManager' => array('privates', 'App\\Common\\Service\\UserManager', 'getUserManagerService.php', true),
));
