<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.WznNWr0' shared service.

return $this->privates['.service_locator.WznNWr0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'orderService' => array('privates', 'App\\Common\\Service\\Order\\OrderService', 'getOrderServiceService.php', true),
));
