<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.5My5vxv' shared service.

return $this->privates['.service_locator.5My5vxv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'form' => array('privates', 'Symfu\\SimpleFormBundle\\Form', 'getFormService.php', true),
    'parameters' => array('privates', 'parameter_bag', 'getParameterBagService', false),
    'translator' => array('services', 'translator', 'getTranslatorService', false),
));
