<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.v2jGrEb' shared service.

return $this->privates['.service_locator.v2jGrEb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'parameters' => array('privates', 'parameter_bag', 'getParameterBagService', false),
));
