<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.te4BFWu' shared service.

return $this->privates['.service_locator.te4BFWu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'form' => array('privates', 'App\\Admin\\Form\\ArticleEditForm', 'getArticleEditFormService.php', true),
    'operatonLogManager' => array('privates', 'App\\Admin\\Service\\AdminOperatonLogManager', 'getAdminOperatonLogManagerService.php', true),
    'uploadFileManager' => array('privates', 'App\\Common\\Service\\FileUpload\\UploadFileManager', 'getUploadFileManagerService.php', true),
));
