<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Common\Bundle\SimplePay\Service\AlipayService' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Common\\Bundle\\SimplePay\\Factory\\PaymentGatewayFactory.php';

return $this->privates['App\Common\Bundle\SimplePay\Service\AlipayService'] = \App\Common\Bundle\SimplePay\Factory\PaymentGatewayFactory::create(($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()), 'alipay', $this->getParameter('simple_pay'));
