<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'League\Flysystem\Filesystem' shared service.

include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\FilesystemInterface.php';
include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\Plugin\\PluggableTrait.php';
include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\ConfigAwareTrait.php';
include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\Filesystem.php';
include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\ReadInterface.php';
include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\AdapterInterface.php';
include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\Adapter\\AbstractAdapter.php';
include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\Adapter\\Local.php';

return $this->services['League\Flysystem\Filesystem'] = new \League\Flysystem\Filesystem(new \League\Flysystem\Adapter\Local(($this->targetDirs[3].'/web/uploads/identity'), 2, 2, array('file' => array('public' => 420, 'private' => 384), 'dir' => array('public' => 493, 'private' => 448))), array('disable_asserts' => false));
