<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Endroid\QrCodeBundle\Controller\GenerateController' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\endroid\\qr-code-bundle\\src\\Controller\\GenerateController.php';

return $this->services['Endroid\QrCodeBundle\Controller\GenerateController'] = new \Endroid\QrCodeBundle\Controller\GenerateController(($this->privates['Endroid\QrCode\Factory\QrCodeFactory'] ?? $this->getQrCodeFactoryService()));
