<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Passport\Service\MobileMsgNoticeService' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\contracts\\Service\\ServiceSubscriberTrait.php';
include_once $this->targetDirs[3].'\\src\\Common\\Service\\BaseService.php';
include_once $this->targetDirs[3].'\\src\\Passport\\Service\\MobileMsgNoticeService.php';

$this->privates['App\Passport\Service\MobileMsgNoticeService'] = $instance = new \App\Passport\Service\MobileMsgNoticeService(($this->services['session'] ?? $this->getSessionService()), ($this->privates['App\Common\Service\SmsService'] ?? $this->load('getSmsServiceService.php')));

$instance->setContainer(($this->privates['.service_locator.fleq5MM'] ?? $this->load('get_ServiceLocator_Fleq5MMService.php'))->withContext('App\\Passport\\Service\\MobileMsgNoticeService', $this));

return $instance;
