<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'oneup_uploader.command.clear_chunks' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\console\\Command\\Command.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\dependency-injection\\ContainerAwareInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Command\\ContainerAwareCommand.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Command\\ClearChunkCommand.php';

$this->privates['oneup_uploader.command.clear_chunks'] = $instance = new \Oneup\UploaderBundle\Command\ClearChunkCommand();

$instance->setName('oneup:uploader:clear-chunks');

return $instance;
