<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Common\Service\Order\OrderService' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\contracts\\Service\\ServiceSubscriberTrait.php';
include_once $this->targetDirs[3].'\\src\\Common\\Service\\BaseService.php';
include_once $this->targetDirs[3].'\\src\\Common\\Service\\Order\\OrderService.php';

$this->privates['App\Common\Service\Order\OrderService'] = $instance = new \App\Common\Service\Order\OrderService(($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()), ($this->privates['App\Reseller\Service\ProductService'] ?? $this->load('getProductServiceService.php')), ($this->privates['App\Common\Service\SystemSettingManager'] ?? $this->load('getSystemSettingManagerService.php')));

$instance->setContainer(($this->privates['.service_locator.fleq5MM'] ?? $this->load('get_ServiceLocator_Fleq5MMService.php'))->withContext('App\\Common\\Service\\Order\\OrderService', $this));

return $instance;
