<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'oneup_uploader.chunk_manager' shared service.

include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Uploader\\Chunk\\ChunkManagerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Uploader\\Chunk\\ChunkManager.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Uploader\\Chunk\\Storage\\ChunkStorageInterface.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Uploader\\Chunk\\Storage\\FilesystemStorage.php';

return $this->services['oneup_uploader.chunk_manager'] = new \Oneup\UploaderBundle\Uploader\Chunk\ChunkManager($this->getParameter('oneup_uploader.chunks'), new \Oneup\UploaderBundle\Uploader\Chunk\Storage\FilesystemStorage(($this->targetDirs[0].'/uploader/chunks')));
