<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'oneup_uploader.controller.identity_image' shared service.

include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Controller\\AbstractController.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Controller\\AbstractChunkedController.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Controller\\DropzoneController.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Uploader\\Storage\\StorageInterface.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Uploader\\Storage\\FlysystemStorage.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Uploader\\ErrorHandler\\ErrorHandlerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Uploader\\ErrorHandler\\DropzoneErrorHandler.php';

return $this->services['oneup_uploader.controller.identity_image'] = new \Oneup\UploaderBundle\Controller\DropzoneController($this, new \Oneup\UploaderBundle\Uploader\Storage\FlysystemStorage(($this->services['League\Flysystem\Filesystem'] ?? $this->load('getFilesystemService.php')), 102400, NULL, ''), ($this->privates['oneup_uploader.error_handler.dropzone'] ?? ($this->privates['oneup_uploader.error_handler.dropzone'] = new \Oneup\UploaderBundle\Uploader\ErrorHandler\DropzoneErrorHandler())), $this->getParameter('oneup_uploader.config.identity_image'), 'identity_image');
