<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Admin\Service\ProductMobileManager' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\contracts\\Service\\ServiceSubscriberTrait.php';
include_once $this->targetDirs[3].'\\src\\Common\\Service\\BaseService.php';
include_once $this->targetDirs[3].'\\src\\Admin\\Service\\AdminBaseService.php';
include_once $this->targetDirs[3].'\\src\\Admin\\Service\\BaseProductManager.php';
include_once $this->targetDirs[3].'\\src\\Admin\\Service\\ProductMobileManager.php';

$this->privates['App\Admin\Service\ProductMobileManager'] = $instance = new \App\Admin\Service\ProductMobileManager(($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));

$instance->setContainer(($this->privates['.service_locator.tw2ef6c'] ?? $this->load('get_ServiceLocator_Tw2ef6cService.php'))->withContext('App\\Admin\\Service\\ProductMobileManager', $this));

return $instance;
