<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'simple_form.validator.custom.recaptcha' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfu\\simple-validation\\src\\ValidatorInterface.php';
include_once $this->targetDirs[3].'\\src\\Common\\Validator\\RecaptchaValidator.php';

return $this->services['simple_form.validator.custom.recaptcha'] = new \App\Common\Validator\RecaptchaValidator(($this->privates['App\Common\Service\RecaptchaService'] ?? $this->load('getRecaptchaServiceService.php')));
