parameters:
    supplier_menus:
        dashboard:
            name: 控制面板
            items:
                -   name: 首页
                    icon: layui-icon-chart
                    url:  /supplier/dashboard
                -   name: 账户信息
                    icon: layui-icon-rmb
                    url:  /supplier/dashboard/profile
                -   name: 平台公告
                    icon: layui-icon-rmb
                    url:  /supplier/dashboard/announcements
                -   name: 操作日记
                    icon: layui-icon-rmb
                    url:  /supplier/dashboard/operation-logs
        orders:
            name: 订单管理
            items:
                -   name: 手机话费充值订单
                    icon: layui-icon-chart
                    url:  /supplier/orders/order-list?product_cate_id=1
                    cate_id: 1
                -   name: 手机流量充值订单
                    icon: layui-icon-chart
                    url:  /supplier/orders/order-list?product_cate_id=4
                    cate_id: 4
                -   name: 固话宽带充值订单
                    icon: layui-icon-rmb
                    url:  /supplier/orders/order-list?product_cate_id=10
                    cate_id: 10
                -   name: 腾讯业务充值订单
                    icon: layui-icon-rmb
                    url:  /supplier/orders/order-list?product_cate_id=3
                    cate_id: 3
        product-sources:
            name: 供货管理
            items:
                -   name: 供货模板管理
                    icon: fa-creative-commons
                    items:
                        - { name: 供货模板管理, route: supplier_product_source_groups_index, icon: fa-list-ul}
#                -   name: 商品管理
#                    icon: fa-shopping-cart
#                    items:
#                        - { name: 手机话费充值, url: /service/service/list, icon: fa-list-ol}
#                        - { name: 手机流量充值, url: /service/service-cate/, icon: fa-certificate}
#                        - { name: 固话宽带充值, url: /service/service-cate/, icon: fa-certificate}
#                        - { name: 腾讯业务充值, url: /service/service-cate/, icon: fa-certificate}
#                -   name: 供货接口秘钥
#                    icon: fa-shopping-cart
#                    items:
#                        - { name: 供货接口秘钥, url: /service/service/list, icon: fa-list-ol}
        finance:
            name: 财务
            items:
                -   name: 账务明细
                    icon: fa-rmb
                    items:
                        - { name: 账户概览, url: /supplier/finance, icon: fa-bank}
                        - { name: 交易记录, url: /supplier/finance/trade-list, icon: fa-hand-rock-o}
                        - { name: 资金明细, url: /supplier/finance/detail, icon: fa-user-md}
                -   name: 提现管理
                    icon: fa-amount
                    items:
                        - { name: 申请提现, url: /supplier/finance/add-withdraw, icon: fa-bank}
                        - { name: 提现记录, url: /supplier/finance/withdraw, icon: fa-hand-rock-o}
                        - { name: 提现账户管理, url: /supplier/finance/withdraw-account, icon: fa-user-md}

#        users:
#            name: 用户管理
#            items:
#                - name: 员工管理
#                  icon: layui-icon-chart
#                  items:
#                      - { name: 员工管理, url: /supplier/users, icon: ""}
#                      - { name: 岗位权限管理, url: /supplier/users/open-account-log, icon: ""}
        passport:
            name: 狐豆通行证
            icon: layui-icon-chart
            url:  /passport/
