<?php

namespace App\Common\Model\User;

use App\Common\Model\AutoGenerated\users_premium_account;
use App\Common\Model\BaseModel;

class UsersPremiumAccount extends users_premium_account
{
    static $table_name = 'yzb_users_premium_account';
}
