<?php

namespace App\Common\Model\User;

use App\Common\Model\AutoGenerated\users_identities;

class UserIdentity extends users_identities {
    static $belongs_to = [
        ['user', ['class_name' => 'User']]
    ];

    // 实名身份认证状态
    const STATUS_NEW      = "NEW"; // 资料不全、没提交审核
    const STATUS_PENDING  = "PENDING"; // 待审核
    const STATUS_REVIEW   = "REVIEW"; // 审核中
    const STATUS_VERIFIED = "VERIFIED"; // 已认证
    const STATUS_REJECTED = "REJECTED"; // 认证失败，未通过

    const STATUSES = [
        self::STATUS_NEW      => '新建',
        self::STATUS_PENDING  => '待审核',
        self::STATUS_REVIEW   => '审核中',
        self::STATUS_VERIFIED => '已认证',
        self::STATUS_REJECTED => '未通过审核',
    ];

    const IMAGE_STATUS_UPLOADED = 'UPLOADED';
    const IMAGE_STATUS_ACCEPTED = 'ACCEPTED';
    const IMAGE_STATUS_REJECTED = 'REJECTED';

    public function isIdentityVerified() {
        return $this->status === self::STATUS_VERIFIED;
    }

}
