<?php
namespace App\Common\Model\User;

use App\Common\Model\AutoGenerated\users_activation_codes;

class UserActivationCode extends users_activation_codes {
    static $table_name = 'yzb_users_activation_codes';

    public function isExpired() {
        return $this->expires_at < time();
    }
}
