framework:
    cache:
        prefix_seed:            foxdou.com
        app:                    app.cache.redis           # App related cache pools configuration
        system:                 cache.adapter.system      # System related cache pools configuration
        directory:              '%kernel.cache_dir%/pools'
        default_redis_provider: '%env(REDIS_URL)%'
#        default_redis_provider: 'redis://redis:9ec2e997f5df4d888be08f605bccd0a0@192.168.1.11:6379/0'
        pools:
            app.cache.apcu:
                adapter: cache.adapter.apcu
                default_lifetime: 1800
            app.cache.redis:
                adapter: cache.adapter.redis
                default_lifetime: 1800
