<?php
namespace App\Common\Model;

use App\Common\Model\AutoGenerated\articles_categories;

class ArticleCategory extends articles_categories {
    static $table_name = 'yzb_articles_categories';
}
