<?php
namespace App\Common\Model;

use App\Common\Model\AutoGenerated\articles;

class Article extends articles {
    static $table_name = 'yzb_articles';

    public function get_cover_image_info($detailed = false) {
        if(!$this->cover_image_id) {
            return null;
        }

        $info = ['id' => $this->cover_image_id, 'url' => $this->cover_image_url, 'name' => pathinfo($this->cover_image_url, PATHINFO_BASENAME )];
        if($detailed && $file = File::find($this->cover_image_id)) {
            $info['size'] = $file->size;
            $info['type'] = $file->type;
        }

        return $info;
    }
}
