<?php
namespace App\Common\Model;

use App\Common\Model\AutoGenerated\icp;

class PhoneNumberAttribution extends icp {
    static $table_name = 'yzb_icp';

    const STATUS_DISABLED = 0;
    const STATUS_ENABLED  = 1;

    const STATUSES = [
        self::STATUS_DISABLED => '停用',
        self::STATUS_ENABLED  => '启用',
    ];
}
