<?php
namespace App\Common\Model;

use App\Common\Model\AutoGenerated\BaseSystemSetting;

class SystemSettingItem extends BaseModel {
    static $table_name = 'yzb_system_settings';

    public static function getSettingItemValue($fields,$options = array()){
        if (is_string($fields)) {
            return self::first(array_merge(['name' => $fields],$options))->value;
        }
        if (is_array($fields)) {
            $data = [];
            foreach ($fields as $field) {
                $data[$field] = self::first(array_merge(['name' => $field],$options))->value;
            }
            return $data;
        }
        return false;
    }
}
