<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pqb1G1K' shared service.

return $this->privates['.service_locator.pqb1G1K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'uploadFileManager' => array('privates', 'App\\Common\\Service\\FileUpload\\UploadFileManager', 'getUploadFileManagerService.php', true),
));
