<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.I8.e3sZ' shared service.

return $this->privates['.service_locator.I8.e3sZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'form' => array('privates', 'App\\Admin\\Form\\RegionEditForm', 'getRegionEditFormService.php', true),
));
