<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vDjLN1k' shared service.

return $this->privates['.service_locator.vDjLN1k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'ipService' => array('privates', 'App\\Passport\\Service\\IpService', 'getIpServiceService.php', true),
));
