<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.B0BYLu.' shared service.

return $this->privates['.service_locator.B0BYLu.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'ispManager' => array('privates', 'App\\Common\\Service\\IspManager', 'getIspManagerService.php', true),
    'productService' => array('privates', 'App\\Reseller\\Service\\ProductService', 'getProductServiceService.php', true),
    'session' => array('services', 'session', 'getSessionService', false),
));
