<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.j6FKjiR' shared service.

return $this->privates['.service_locator.j6FKjiR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'form' => array('privates', 'Symfu\\SimpleFormBundle\\Form', 'getFormService.php', true),
    'identityVerifyService' => array('privates', 'App\\Common\\Service\\ExternalService\\IdentityVerifyService', 'getIdentityVerifyServiceService.php', true),
    'session' => array('services', 'session', 'getSessionService', false),
    'settings' => array('privates', 'App\\Common\\Service\\SystemSetting', 'getSystemSettingService', false),
));
