<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.kHm4B1b' shared service.

return $this->privates['.service_locator.kHm4B1b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'csrfTokenManager' => array('services', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService.php', true),
));
