<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fleq5MM' shared service.

return $this->privates['.service_locator.fleq5MM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'App\\Common\\Service\\BaseService::logger' => array('privates', 'monolog.logger', 'getMonolog_LoggerService', false),
    'App\\Common\\Service\\BaseService::settings' => array('privates', 'App\\Common\\Service\\SystemSetting', 'getSystemSettingService', false),
));
