<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ErQKBbM' shared service.

return $this->privates['.service_locator.ErQKBbM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'passportSettingForm' => array('privates', 'App\\Admin\\Form\\SystemSetting\\PassportSettingForm', 'getPassportSettingFormService.php', true),
    'resellerPlatformSettingForm' => array('privates', 'App\\Admin\\Form\\SystemSetting\\ResellerPlatformSettingForm', 'getResellerPlatformSettingFormService.php', true),
    'settings' => array('privates', 'App\\Common\\Service\\SystemSetting', 'getSystemSettingService', false),
    'supplierPlatformSettingForm' => array('privates', 'App\\Admin\\Form\\SystemSetting\\SupplierPlatformSettingForm', 'getSupplierPlatformSettingFormService.php', true),
    'systemForm' => array('privates', 'App\\Admin\\Form\\SystemSetting\\SystemForm', 'getSystemFormService.php', true),
));
