<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qFNxiTm' shared service.

return $this->privates['.service_locator.qFNxiTm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'Symfu\\SimpleFormBundle\\Form::csrfTokenManager' => array('services', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService.php', true),
    'Symfu\\SimpleFormBundle\\Form::parameters' => array('privates', 'parameter_bag', 'getParameterBagService', false),
    'Symfu\\SimpleFormBundle\\Form::requestStack' => array('services', 'request_stack', 'getRequestStackService', false),
    'Symfu\\SimpleFormBundle\\Form::session' => array('services', 'session', 'getSessionService', false),
    'Symfu\\SimpleFormBundle\\Form::transformerMgr' => array('services', 'Symfu\\SimpleValidation\\TransformerManagerInterface', 'getTransformerManagerInterfaceService.php', true),
    'Symfu\\SimpleFormBundle\\Form::translator' => array('services', 'translator', 'getTranslatorService', false),
    'Symfu\\SimpleFormBundle\\Form::validatorMgr' => array('services', 'Symfu\\SimpleValidation\\ValidationManagerInterface', 'getValidationManagerInterfaceService.php', true),
));
