<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Common\Service\ArticleManager' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Common\\Service\\ArticleManager.php';

return $this->privates['App\Common\Service\ArticleManager'] = new \App\Common\Service\ArticleManager();
