<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'cache.app.simple' shared service.

include_once $this->targetDirs[3].'\\vendor\\psr\\simple-cache\\src\\CacheInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\cache\\Traits\\ProxyTrait.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\cache\\Simple\\Psr6Cache.php';

return $this->privates['cache.app.simple'] = new \Symfony\Component\Cache\Simple\Psr6Cache(($this->services['cache.app'] ?? $this->load('getCache_AppService.php')));
