<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'oneup_uploader.orphanage_manager' shared service.

include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Uploader\\Orphanage\\OrphanageManager.php';

return $this->services['oneup_uploader.orphanage_manager'] = new \Oneup\UploaderBundle\Uploader\Orphanage\OrphanageManager($this, $this->getParameter('oneup_uploader.orphanage'));
