<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'oneup_uploader.controller.admin_article' shared service.

include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Controller\\AbstractController.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Controller\\AbstractChunkedController.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Controller\\DropzoneController.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Uploader\\Storage\\StorageInterface.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Uploader\\Storage\\FlysystemStorage.php';
include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\FilesystemInterface.php';
include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\Plugin\\PluggableTrait.php';
include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\ConfigAwareTrait.php';
include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\Filesystem.php';
include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\ReadInterface.php';
include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\AdapterInterface.php';
include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\Adapter\\AbstractAdapter.php';
include_once $this->targetDirs[3].'\\vendor\\league\\flysystem\\src\\Adapter\\Local.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Uploader\\ErrorHandler\\ErrorHandlerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\oneup\\uploader-bundle\\Uploader\\ErrorHandler\\DropzoneErrorHandler.php';

return $this->services['oneup_uploader.controller.admin_article'] = new \Oneup\UploaderBundle\Controller\DropzoneController($this, new \Oneup\UploaderBundle\Uploader\Storage\FlysystemStorage(new \League\Flysystem\Filesystem(new \League\Flysystem\Adapter\Local(($this->targetDirs[3].'/web/uploads/article'), 2, 2, array('file' => array('public' => 420, 'private' => 384), 'dir' => array('public' => 493, 'private' => 448))), array('disable_asserts' => false)), 102400, NULL, ''), ($this->privates['oneup_uploader.error_handler.dropzone'] ?? ($this->privates['oneup_uploader.error_handler.dropzone'] = new \Oneup\UploaderBundle\Uploader\ErrorHandler\DropzoneErrorHandler())), $this->getParameter('oneup_uploader.config.admin_article'), 'admin_article');
