<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'simple_form.validator.custom.verify_code' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfu\\simple-validation\\src\\ValidatorInterface.php';
include_once $this->targetDirs[3].'\\src\\Common\\Validator\\VerifyCodeValidator.php';

return $this->services['simple_form.validator.custom.verify_code'] = new \App\Common\Validator\VerifyCodeValidator(($this->privates['App\Common\Service\SmsService'] ?? $this->load('getSmsServiceService.php')));
