<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'services_resetter' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\DependencyInjection\\ServicesResetter.php';

return $this->services['services_resetter'] = new \Symfony\Component\HttpKernel\DependencyInjection\ServicesResetter(new RewindableGenerator(function () {
    if (isset($this->privates['App\Admin\Form\AdminEditForm'])) {
        yield 'App\\Admin\\Form\\AdminEditForm' => ($this->privates['App\Admin\Form\AdminEditForm'] ?? null);
    }
    if (isset($this->privates['App\Admin\Form\ArticleEditForm'])) {
        yield 'App\\Admin\\Form\\ArticleEditForm' => ($this->privates['App\Admin\Form\ArticleEditForm'] ?? null);
    }
    if (isset($this->privates['App\Admin\Form\PhoneNumberAttributionEditForm'])) {
        yield 'App\\Admin\\Form\\PhoneNumberAttributionEditForm' => ($this->privates['App\Admin\Form\PhoneNumberAttributionEditForm'] ?? null);
    }
    if (false) {
        yield 'App\\Admin\\Form\\ProductSearchForm' => null;
    }
    if (isset($this->privates['App\Admin\Form\RegionEditForm'])) {
        yield 'App\\Admin\\Form\\RegionEditForm' => ($this->privates['App\Admin\Form\RegionEditForm'] ?? null);
    }
    if (isset($this->privates['App\Admin\Form\SystemSetting\PassportSettingForm'])) {
        yield 'App\\Admin\\Form\\SystemSetting\\PassportSettingForm' => ($this->privates['App\Admin\Form\SystemSetting\PassportSettingForm'] ?? null);
    }
    if (isset($this->privates['App\Admin\Form\SystemSetting\ResellerPlatformSettingForm'])) {
        yield 'App\\Admin\\Form\\SystemSetting\\ResellerPlatformSettingForm' => ($this->privates['App\Admin\Form\SystemSetting\ResellerPlatformSettingForm'] ?? null);
    }
    if (isset($this->privates['App\Admin\Form\SystemSetting\SupplierPlatformSettingForm'])) {
        yield 'App\\Admin\\Form\\SystemSetting\\SupplierPlatformSettingForm' => ($this->privates['App\Admin\Form\SystemSetting\SupplierPlatformSettingForm'] ?? null);
    }
    if (isset($this->privates['App\Admin\Form\SystemSetting\SystemForm'])) {
        yield 'App\\Admin\\Form\\SystemSetting\\SystemForm' => ($this->privates['App\Admin\Form\SystemSetting\SystemForm'] ?? null);
    }
    if (false) {
        yield 'App\\Admin\\Form\\TencentProductCategoryEditForm' => null;
    }
    if (isset($this->privates['App\Admin\Form\VirtualNetworkOperatorEditForm'])) {
        yield 'App\\Admin\\Form\\VirtualNetworkOperatorEditForm' => ($this->privates['App\Admin\Form\VirtualNetworkOperatorEditForm'] ?? null);
    }
    if (false) {
        yield 'App\\Common\\Form\\IndividualUserRegisterForm' => null;
    }
    if (isset($this->privates['App\Common\Form\UserForm'])) {
        yield 'App\\Common\\Form\\UserForm' => ($this->privates['App\Common\Form\UserForm'] ?? null);
    }
    if (false) {
        yield 'App\\Common\\Service\\Cache\\AppCacheRedis' => null;
    }
    if (isset($this->privates['App\Common\Service\Cache\ChainCache'])) {
        yield 'App\\Common\\Service\\Cache\\ChainCache' => ($this->privates['App\Common\Service\Cache\ChainCache'] ?? null);
    }
    if (false) {
        yield 'App\\Common\\Service\\SimpleRecordResetter' => null;
    }
    if (isset($this->privates['App\Passport\Form\BusinessIdentitySubmitForm'])) {
        yield 'App\\Passport\\Form\\BusinessIdentitySubmitForm' => ($this->privates['App\Passport\Form\BusinessIdentitySubmitForm'] ?? null);
    }
    if (isset($this->privates['App\Passport\Form\IndividualIdentitySubmitForm'])) {
        yield 'App\\Passport\\Form\\IndividualIdentitySubmitForm' => ($this->privates['App\Passport\Form\IndividualIdentitySubmitForm'] ?? null);
    }
    if (false) {
        yield 'App\\Reseller\\Form\\OrderRechargeForm' => null;
    }
    if (isset($this->privates['App\Reseller\Form\PrintSettingForm'])) {
        yield 'App\\Reseller\\Form\\PrintSettingForm' => ($this->privates['App\Reseller\Form\PrintSettingForm'] ?? null);
    }
    if (isset($this->privates['App\Reseller\Form\TransferForm'])) {
        yield 'App\\Reseller\\Form\\TransferForm' => ($this->privates['App\Reseller\Form\TransferForm'] ?? null);
    }
    if (false) {
        yield 'App\\Supplier\\Form\\BusinessIdentitySubmitForm' => null;
    }
    if (isset($this->privates['App\Test\Form\TestForm'])) {
        yield 'App\\Test\\Form\\TestForm' => ($this->privates['App\Test\Form\TestForm'] ?? null);
    }
    if (isset($this->privates['http_exception_listener'])) {
        yield 'http_exception_listener' => ($this->privates['http_exception_listener'] ?? null);
    }
    if (isset($this->privates['debug.stopwatch'])) {
        yield 'debug.stopwatch' => ($this->privates['debug.stopwatch'] ?? null);
    }
    if (isset($this->services['security.token_storage'])) {
        yield 'security.token_storage' => ($this->services['security.token_storage'] ?? null);
    }
    if (isset($this->privates['swiftmailer.email_sender.listener'])) {
        yield 'swiftmailer.email_sender.listener' => ($this->privates['swiftmailer.email_sender.listener'] ?? null);
    }
    if (isset($this->privates['Symfu\SimpleFormBundle\Form'])) {
        yield 'Symfu\\SimpleFormBundle\\Form' => ($this->privates['Symfu\SimpleFormBundle\Form'] ?? null);
    }
}, function () {
    return 0 + (int) (isset($this->privates['App\Admin\Form\AdminEditForm'])) + (int) (isset($this->privates['App\Admin\Form\ArticleEditForm'])) + (int) (isset($this->privates['App\Admin\Form\PhoneNumberAttributionEditForm'])) + (int) (false) + (int) (isset($this->privates['App\Admin\Form\RegionEditForm'])) + (int) (isset($this->privates['App\Admin\Form\SystemSetting\PassportSettingForm'])) + (int) (isset($this->privates['App\Admin\Form\SystemSetting\ResellerPlatformSettingForm'])) + (int) (isset($this->privates['App\Admin\Form\SystemSetting\SupplierPlatformSettingForm'])) + (int) (isset($this->privates['App\Admin\Form\SystemSetting\SystemForm'])) + (int) (false) + (int) (isset($this->privates['App\Admin\Form\VirtualNetworkOperatorEditForm'])) + (int) (false) + (int) (isset($this->privates['App\Common\Form\UserForm'])) + (int) (false) + (int) (isset($this->privates['App\Common\Service\Cache\ChainCache'])) + (int) (false) + (int) (isset($this->privates['App\Passport\Form\BusinessIdentitySubmitForm'])) + (int) (isset($this->privates['App\Passport\Form\IndividualIdentitySubmitForm'])) + (int) (false) + (int) (isset($this->privates['App\Reseller\Form\PrintSettingForm'])) + (int) (isset($this->privates['App\Reseller\Form\TransferForm'])) + (int) (false) + (int) (isset($this->privates['App\Test\Form\TestForm'])) + (int) (isset($this->privates['http_exception_listener'])) + (int) (isset($this->privates['debug.stopwatch'])) + (int) (isset($this->services['security.token_storage'])) + (int) (isset($this->privates['swiftmailer.email_sender.listener'])) + (int) (isset($this->privates['Symfu\SimpleFormBundle\Form']));
}), array('App\\Admin\\Form\\AdminEditForm' => 'reset', 'App\\Admin\\Form\\ArticleEditForm' => 'reset', 'App\\Admin\\Form\\PhoneNumberAttributionEditForm' => 'reset', 'App\\Admin\\Form\\ProductSearchForm' => 'reset', 'App\\Admin\\Form\\RegionEditForm' => 'reset', 'App\\Admin\\Form\\SystemSetting\\PassportSettingForm' => 'reset', 'App\\Admin\\Form\\SystemSetting\\ResellerPlatformSettingForm' => 'reset', 'App\\Admin\\Form\\SystemSetting\\SupplierPlatformSettingForm' => 'reset', 'App\\Admin\\Form\\SystemSetting\\SystemForm' => 'reset', 'App\\Admin\\Form\\TencentProductCategoryEditForm' => 'reset', 'App\\Admin\\Form\\VirtualNetworkOperatorEditForm' => 'reset', 'App\\Common\\Form\\IndividualUserRegisterForm' => 'reset', 'App\\Common\\Form\\UserForm' => 'reset', 'App\\Common\\Service\\Cache\\AppCacheRedis' => 'reset', 'App\\Common\\Service\\Cache\\ChainCache' => 'reset', 'App\\Common\\Service\\SimpleRecordResetter' => 'reset', 'App\\Passport\\Form\\BusinessIdentitySubmitForm' => 'reset', 'App\\Passport\\Form\\IndividualIdentitySubmitForm' => 'reset', 'App\\Reseller\\Form\\OrderRechargeForm' => 'reset', 'App\\Reseller\\Form\\PrintSettingForm' => 'reset', 'App\\Reseller\\Form\\TransferForm' => 'reset', 'App\\Supplier\\Form\\BusinessIdentitySubmitForm' => 'reset', 'App\\Test\\Form\\TestForm' => 'reset', 'http_exception_listener' => 'reset', 'debug.stopwatch' => 'reset', 'security.token_storage' => 'setToken', 'swiftmailer.email_sender.listener' => 'reset', 'Symfu\\SimpleFormBundle\\Form' => 'reset'));
