<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Symfu\SimpleValidation\TransformerManagerInterface' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfu\\simple-validation\\src\\TransformerManagerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfu\\simple-validation\\src\\TransformerManager.php';
include_once $this->targetDirs[3].'\\vendor\\symfu\\simple-form-bundle\\src\\TransformerManager.php';

return $this->services['Symfu\SimpleValidation\TransformerManagerInterface'] = new \Symfu\SimpleFormBundle\TransformerManager($this);
