<?php
namespace App\Common\Model\Product;

use App\Common\Model\AttributedModel;
use App\Common\Model\AutoGenerated\product_setting;
use App\Common\Model\BaseModel;

class ProductSetting extends product_setting {
    static $table_name = 'product_setting';

}
