<?php
namespace App\Common\Model\Product;

use App\Common\Model\AttributedModel;
use App\Common\Model\AutoGenerated\product_source;
use App\Common\Model\BaseModel;

class ProductSource extends product_source {
}
