<?php
namespace App\Common\Model\Product;

use App\Common\Model\AutoGenerated\product_tencent_categories;
use App\Common\Model\AutoGenerated\tencent_product_categories;

class ProductTencentCategory extends product_tencent_categories {
    const SUPER_CATEGORY_CREDIT       = 'CREDIT';
    const SUPER_CATEGORY_SUBSCRIPTION = 'SUBSCRIPTION';

    const SUPER_CATEGORIES = [
        self::SUPER_CATEGORY_CREDIT        => 'Q币/点/券直充类',
        self::SUPER_CATEGORY_SUBSCRIPTION  => '包月会员服务类',
    ];

    const STATUS_DISABLED = 0;
    const STATUS_ENABLED  = 1;

    const STATUSES = [
        self::STATUS_DISABLED => '禁用',
        self::STATUS_ENABLED  => '启用',
    ];

    public static function getCategories($useCache = true) {
        static $categories = null;

        if($categories === null || !$useCache) {
            $rows = self::all(['enabled' => self::STATUS_ENABLED]);
            $categories = [];
            foreach ($rows as $row) {
                $categories[$row['id']] = $row['name'];
            }
        }

        return $categories;
    }
}
