<?php

namespace App\Reseller\Model;

use App\Common\Model\AutoGenerated\agent_users_print_settings;
use App\Common\Model\BaseModel;

class PrinterSetting extends agent_users_print_settings {
    static $table_name = 'yzb_agent_users_print_settings';

    const PRINTER_THERMAL_58MM = "THERMAL_58MM";
    const PRINTER_GENERIC = "GENERIC";

    const PRINT_TYPES = [
        self::PRINTER_THERMAL_58MM,
        self::PRINTER_GENERIC,
    ];

    const DEFAULT_VISIBLE_SETTINGS = [
        'add_time'        => 1,
        'cashier'         => 1,
        'contact_mobile'  => 1,
        'foot'            => 1,
        'on'              => 1,
        'on_before_info'  => 0,
        'order_id'        => 1,
        'pay_money'       => 1,
        'product_name'    => 1,
        'recharge_amount' => 1,
        'shop_address'    => 1,
        'shop_name'       => 1,
        'title'           => 1,
    ];
}
